# Generated by Django 5.2.7 on 2025-11-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0002_alter_battle_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
