# Generated by Django 5.2.7 on 2025-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0003_battle_battle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reference_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sample_io',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
