# Generated by Django 5.2.7 on 2025-11-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0004_challenge_language_challenge_reference_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='challenge',
        ),
        migrations.AddField(
            model_name='battle',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='codebattle.challenge'),
        ),
        migrations.AddField(
            model_name='battle',
            name='current_challenge_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='battle',
            name='num_questions',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='battle',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
