# Generated by Django 5.2.7 on 2025-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0005_remove_battle_challenge_battle_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
