# Generated by Django 5.2.7 on 2025-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0006_battle_player1_ready_battle_player2_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='question_winners',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
