# Generated by Django 5.2.7 on 2025-11-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0007_battle_question_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
    ]
