# Generated by Django 5.2.7 on 2025-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebattle', '0008_alter_challenge_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
