# Generated by Django 5.2.7 on 2025-11-19 18:05

import django.db.models.deletion
from django.db import migrations, models
import secrets
import string


def generate_room_code():
    """Generate a unique 6-character room code"""
    return ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(6))


def populate_room_codes(apps, schema_editor):
    """Populate room_code for existing rooms"""
    Room = apps.get_model('multiplayer', 'Room')
    for room in Room.objects.all():
        if not room.room_code:
            # Generate unique code
            while True:
                code = generate_room_code()
                if not Room.objects.filter(room_code=code).exists():
                    room.room_code = code
                    room.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
        ('quizzes', '0007_gamesession_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='num_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.topic'),
        ),
        migrations.AlterField(
            model_name='room',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.RunPython(populate_room_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
