# Generated by Django 5.2.7 on 2025-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_room_level_room_num_questions_room_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='answered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='quiz_state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('finished', 'Finished')], default='not_started', max_length=20),
        ),
    ]
