# Generated by Django 5.2.7 on 2025-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_room_answered_count_room_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='webrtc_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='webrtc_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='round_state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('complete', 'Complete'), ('countdown', 'Countdown to Next')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
