# Generated by Django 5.2.7 on 2025-11-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0005_auto_20251122_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='webrtc_offer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='timer_start',
        ),
    ]
