# Generated by Django 5.2.7 on 2025-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_description_quiz_difficulty_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
