# Generated by Django 5.2.7 on 2025-11-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_gamesession_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
