# Generated by Django 5.2.7 on 2025-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_question_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
