# Generated by Django 5.2.7 on 2025-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
