# Generated by Django 5.2.7 on 2025-11-26 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_userprogress_level_userprogress_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
